/*
 zoddjs v0.0.3 - a tiny loading bar for modernizr/yepnope
 copyright 2014 kevin von flotow - vonflow@gmail.com
 https://github.com/kvonflotow/zoddjs
 MIT license
*/
(function(c,h){function d(a,b){for(var f in b)a.style[f]=b[f]}function l(a){return"string"===typeof a||a instanceof String}function k(){var a=arguments;1===a.length&&p(a[0])&&(a=a[0]);var b=a[0]||[];if(2<=a.length)for(var f=1,c=a.length;f<c;f+=1)if("undefined"!==typeof a[f])for(var e in a[f])"undefined"!==typeof e&&(b[e]=a[f][e]);return b}function m(a,b){this.arr=a||[];this.opts=b||{};this.loaderModal=g.createElement("div");this.loadingBar=g.createElement("div");this.loaded=this.loadPercent=0;this.count=
this.arr.length;this.noTarget=!1;this.setDefaultOpts();this.init()}var n=c.Modernizr&&c.Modernizr.load?c.Modernizr.load:c.yepnope?c.yepnope:h;if(!n)return console.error("zodd: modernizr or yepnope is required");var g=c.document,p=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};m.prototype={setDefaultOpts:function(){this.opts.scrollDuration="undefined"!==typeof this.opts.scrollDuration?this.opts.scrollDuration:0.33;if(this.opts.targetElementById&&l(this.opts.targetElementById))this.opts.targetElement=
document.getElementById(this.opts.targetElementById);else{var a=this.opts,b;(b=this.opts.targetElement)||(b=g.getElementsByTagName("body"),this.noTarget=!0,b=0!==b.length?b[0]:h);a.targetElement=b}this.opts.css=this.opts.css||{};this.opts.css.modal=k({"background-color":"rgb( 233, 233, 233 )",position:this.noTarget?"fixed":"absolute",top:"0",bottom:"0",left:"0",right:"0",opacity:"1","-webkit-transition":"opacity 0.5s","-moz-transition":"opacity 0.5s","-o-transition":"opacity 0.5s",transition:"opacity 0.5s"},
this.opts.css.modal||{});this.opts.css.loadingBarWrapper=k({position:"absolute",top:"50%",left:"0",right:"0",width:"80%",height:"5px",margin:"auto","border-radius":"2px"},this.opts.css.loadingBarWrapper||{});this.opts.css.loadingBar=k({"background-color":"rgb( 69, 154, 188 )",width:"0%",height:"100%","border-radius":"2px","-webkit-transition":"width "+this.opts.scrollDuration+"s","-moz-transition":"width "+this.opts.scrollDuration+"s","-o-transition":"width "+this.opts.scrollDuration+"s",transition:"width "+
this.opts.scrollDuration+"s"},this.opts.css.loadingBar||{})},init:function(){var a=g.createElement("div");this.count=this.arr.length;d(this.loaderModal,this.opts.css.modal);d(a,this.opts.css.loadingBarWrapper);this.loadingBar=g.createElement("div");d(this.loadingBar,this.opts.css.loadingBar);a.appendChild(this.loadingBar);this.loaderModal.appendChild(a);this.noTarget||this.opts.targetElement.style.position||d(this.opts.targetElement,{position:"relative"});this.opts.targetElement.appendChild(this.loaderModal);
var b=this;n(function(){for(var a=[],c=0;c<b.count;c+=1){var e=b.arr[c],d={};if(l(e))d={load:e};else for(var g in e)d[g]=e[g];e=d.hasOwnProperty("complete")?d.complete:h;d.complete=function(a){return function(){b.addOneToLoaded.call(b);a&&a()}}(e);a.push(d)}return a}())},addOneToLoaded:function(){this.loadPercent=100*(this.loaded+=1/this.count)+0.5|0;d(this.loadingBar,{width:this.loadPercent+"%"});if(100===this.loadPercent){this.opts.targetElement.setAttribute("data-loader-loaded",!0);var a=this;
setTimeout(function(){d(a.loaderModal,{opacity:"0"});setTimeout(function(){d(a.loaderModal,{display:"none"});a.loaderModal.remove&&a.loaderModal.remove()},500)},250)}}};c.zodd=m})(window,void 0);
