/*
 zoddjs v0.0.1 - a tiny loading bar for modernizr/yepnope
 copyright 2014 kevin von flotow - vonflow@gmail.com
 MIT license
*/
(function(l,n,h){function c(a,b){for(var d in b)a.style[d]=b[d]}function f(){var a=arguments;1===a.length&&p(a[0])&&(a=a[0]);var b=a[0]||[];if(2<=a.length)for(var d=1,c=a.length;d<c;d+=1)if("undefined"!==typeof a[d])for(var k in a[d])"undefined"!==typeof k&&(b[k]=a[d][k]);return b}function m(a,b){this.arr=a||[];this.opts=b||{};this.setDefaultOpts();this.firstBody=h;this.loaderModal=e.createElement("div");this.loadingBar=e.createElement("div");this.loaded=this.loadPercent=0;this.count=this.arr.length;
this.init()}var e=l.document,p=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};m.prototype={setDefaultOpts:function(){this.opts.scrollDuration=0.33;this.opts.css=this.opts.css||{};this.opts.css.modal=f({background:"rgb( 233, 233, 233 )",position:"fixed",top:"0",bottom:"0",left:"0",right:"0",opacity:"1","-webkit-transition":"opacity 0.5s","-moz-transition":"opacity 0.5s","-o-transition":"opacity 0.5s",transition:"opacity 0.5s"},this.opts.css.modal||{});this.opts.css.loadingBarWrapper=
f({position:"absolute",top:"50%",left:"0",right:"0",width:"80%",height:"5px",margin:"auto","border-radius":"2px"},this.opts.css.loadingBarWrapper||{});this.opts.css.loadingBar=f({background:"rgb( 69, 154, 188 )",width:"0%",height:"100%","border-radius":"2px","-webkit-transition":"width "+this.opts.scrollDuration+"s","-moz-transition":"width "+this.opts.scrollDuration+"s","-o-transition":"width "+this.opts.scrollDuration+"s",transition:"width "+this.opts.scrollDuration+"s"},this.opts.css.loadingBar||
{})},init:function(){var a=e.getElementsByTagName("body"),b=e.createElement("div");this.firstBody=0!==a.length?a[0]:h;this.count=this.arr.length;c(this.loaderModal,this.opts.css.modal);c(b,this.opts.css.loadingBarWrapper);this.loadingBar=e.createElement("div");c(this.loadingBar,this.opts.css.loadingBar);b.appendChild(this.loadingBar);this.loaderModal.appendChild(b);this.firstBody.appendChild(this.loaderModal);var d=this;n.load(function(){for(var a=[],b=0;b<d.count;b+=1){var c=d.arr[b],g={};if("string"===
typeof c||c instanceof String)g={load:c};else for(var e in c)g[e]=c[e];var f=g.hasOwnProperty("complete")?g.complete:h;g.complete=function(){f&&f();d.addOneToLoaded.call(d)};a.push(g)}return a}())},addOneToLoaded:function(){this.loadPercent=100*(this.loaded+=1/this.count)+0.5|0;if(this.loaderModal&&(c(this.loadingBar,{width:this.loadPercent+"%"}),100===this.loadPercent)){this.firstBody.setAttribute("data-loader-loaded",!0);var a=this;setTimeout(function(){c(a.loaderModal,{opacity:"0"});setTimeout(function(){c(a.loaderModal,
{display:"none"});a.loaderModal.remove&&a.loaderModal.remove()},500)},250)}}};l.zodd=m})(window,Modernizr||yepnope,void 0);
